services:
  - type: web
    name: relaciona-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn nombre_proyecto.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: nombre_proyecto.settings
      - key: PYTHON_VERSION
        value: 3.11