services:
  - type: web
    name: relaciona-app
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn relaciona.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: relaciona.settings
      - key: PYTHON_VERSION
        value: 3.11